"""initial schema

Revision ID: 0f5f739b07b7
Revises: 
Create Date: 2026-04-27 14:42:25.742611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5f739b07b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_code', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('definition_scope', sa.Text(), nullable=False),
    sa.Column('reference_documents', sa.Text(), nullable=False),
    sa.Column('compliance_framework', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_code')
    )
    op.create_index('ix_clients_client_name', 'clients', ['client_name'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('permission_label', sa.String(length=255), nullable=True),
    sa.Column('permission_description', sa.String(length=500), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_key')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_access_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.BigInteger(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('versions',
    sa.Column('version_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=True),
    sa.Column('released_at', sa.BigInteger(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('ix_versions_is_current', 'versions', ['is_current'], unique=True, postgresql_where='is_current')
    op.create_table('control_repository',
    sa.Column('control_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('control_number', sa.String(length=255), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('control_desc', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('pwc_reliance', sa.String(length=255), nullable=True),
    sa.Column('control_owner', sa.BigInteger(), nullable=False),
    sa.Column('units_fccg_contact', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['control_owner'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['units_fccg_contact'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.version_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('control_id')
    )
    op.create_index('ix_control_repository_control_number', 'control_repository', ['control_number'], unique=False)
    op.create_index('ix_control_repository_control_owner', 'control_repository', ['control_owner'], unique=False)
    op.create_index('ix_control_repository_domain', 'control_repository', ['domain'], unique=False)
    op.create_index('ix_control_repository_status', 'control_repository', ['status'], unique=False)
    op.create_index('ix_control_repository_units_fccg_contact', 'control_repository', ['units_fccg_contact'], unique=False)
    op.create_index('ix_control_repository_version_id', 'control_repository', ['version_id'], unique=False)
    op.create_table('review_cycles',
    sa.Column('cycle_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('project_lead', sa.BigInteger(), nullable=True),
    sa.Column('review_period', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('audit_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.BigInteger(), nullable=False),
    sa.Column('due_date', sa.BigInteger(), nullable=False),
    sa.Column('end_date', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_review_cycles_end_gte_start'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_review_cycles_score_range'),
    sa.CheckConstraint('start_date <= due_date', name='ck_review_cycles_start_lte_due'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_lead'], ['users.user_id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('cycle_id')
    )
    op.create_index('ix_review_cycles_client_id', 'review_cycles', ['client_id'], unique=False)
    op.create_index('ix_review_cycles_project_lead', 'review_cycles', ['project_lead'], unique=False)
    op.create_index('ix_review_cycles_status', 'review_cycles', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_permission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('role_permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_perm')
    )
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_role')
    )
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_table('config_controls',
    sa.Column('config_control_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('control_id', sa.BigInteger(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control_repository.control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.cycle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('config_control_id'),
    sa.UniqueConstraint('cycle_id', 'control_id', name='uq_config_controls_cycle_control')
    )
    op.create_index('ix_config_controls_control_id', 'config_controls', ['control_id'], unique=False)
    op.create_table('control_change_log',
    sa.Column('change_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('from_version', sa.BigInteger(), nullable=True),
    sa.Column('to_version', sa.BigInteger(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('new_control_name', sa.String(length=255), nullable=True),
    sa.Column('new_control_desc', sa.Text(), nullable=True),
    sa.Column('change_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('change_percentage IS NULL OR (change_percentage >= 0 AND change_percentage <= 100)', name='ck_control_change_log_pct_range'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_id'], ['control_repository.control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_version'], ['versions.version_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_version'], ['versions.version_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index('ix_control_change_log_changed_by', 'control_change_log', ['changed_by'], unique=False)
    op.create_index('ix_control_change_log_control_id', 'control_change_log', ['control_id'], unique=False)
    op.create_index('ix_control_change_log_from_version', 'control_change_log', ['from_version'], unique=False)
    op.create_index('ix_control_change_log_to_version', 'control_change_log', ['to_version'], unique=False)
    op.create_table('control_frameworks',
    sa.Column('control_framework_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.BigInteger(), nullable=False),
    sa.Column('framework_name', sa.String(length=100), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['control_repository.control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('control_framework_id'),
    sa.UniqueConstraint('control_id', 'framework_name', name='uq_control_frameworks_ctrl_fw')
    )
    op.create_index('ix_control_frameworks_framework_name', 'control_frameworks', ['framework_name'], unique=False)
    op.create_table('engagement_team',
    sa.Column('engagement_team_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('team_role', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.cycle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('engagement_team_id'),
    sa.UniqueConstraint('cycle_id', 'user_id', name='uq_engagement_team_cycle_user')
    )
    op.create_index('ix_engagement_team_user_id', 'engagement_team', ['user_id'], unique=False)
    op.create_table('control_tests_and_evidences',
    sa.Column('test_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_control_id', sa.BigInteger(), nullable=False),
    sa.Column('tests', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['config_control_id'], ['config_controls.config_control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index('ix_control_tests_config_control_id', 'control_tests_and_evidences', ['config_control_id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('evidence_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('upload_date', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=True),
    sa.Column('control_id', sa.BigInteger(), nullable=True),
    sa.Column('test_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('file_version', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('cycle_id IS NOT NULL OR control_id IS NOT NULL OR test_id IS NOT NULL', name='ck_evidence_files_linkage'),
    sa.ForeignKeyConstraint(['control_id'], ['control_repository.control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.cycle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['control_tests_and_evidences.test_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index('ix_evidence_files_control_id', 'evidence_files', ['control_id'], unique=False)
    op.create_index('ix_evidence_files_cycle_id', 'evidence_files', ['cycle_id'], unique=False)
    op.create_index('ix_evidence_files_status', 'evidence_files', ['status'], unique=False)
    op.create_index('ix_evidence_files_test_id', 'evidence_files', ['test_id'], unique=False)
    op.create_index('ix_evidence_files_uploaded_by', 'evidence_files', ['uploaded_by'], unique=False)
    op.create_table('test_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=True),
    sa.Column('control_id', sa.BigInteger(), nullable=True),
    sa.Column('cycle_id', sa.BigInteger(), nullable=True),
    sa.Column('log_date', sa.BigInteger(), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('execution_time_seconds', sa.BigInteger(), nullable=True),
    sa.Column('report_link', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_time', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('test_id IS NOT NULL OR control_id IS NOT NULL OR cycle_id IS NOT NULL', name='ck_test_logs_linkage'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_id'], ['control_repository.control_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['review_cycles.cycle_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['control_tests_and_evidences.test_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_test_logs_changed_by', 'test_logs', ['changed_by'], unique=False)
    op.create_index('ix_test_logs_control_id', 'test_logs', ['control_id'], unique=False)
    op.create_index('ix_test_logs_cycle_id', 'test_logs', ['cycle_id'], unique=False)
    op.create_index('ix_test_logs_test_id', 'test_logs', ['test_id'], unique=False)
    op.create_table(
        'control_test_results',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('test_id', sa.Integer(), nullable=False),
        sa.Column('control_id', sa.String(length=255), nullable=False),
        sa.Column('cycle_id', sa.Integer(), nullable=False),
        sa.Column('compliance_test', sa.String(length=50), nullable=False),
        sa.Column('audit_justification', sa.Text(), nullable=True),
        sa.Column('task_id', sa.String(length=255), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('execution_status', sa.String(length=100), nullable=True),
        sa.Column('user_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        'ix_control_test_results_test_id',
        'control_test_results',
        ['test_id'],
        unique=False
    )

    op.create_index(
        'ix_control_test_results_control_id',
        'control_test_results',
        ['control_id'],
        unique=False
    )

    op.create_index(
        'ix_control_test_results_cycle_id',
        'control_test_results',
        ['cycle_id'],
        unique=False
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_test_logs_test_id', table_name='test_logs')
    op.drop_index('ix_test_logs_cycle_id', table_name='test_logs')
    op.drop_index('ix_test_logs_control_id', table_name='test_logs')
    op.drop_index('ix_test_logs_changed_by', table_name='test_logs')
    op.drop_table('test_logs')
    op.drop_index('ix_evidence_files_uploaded_by', table_name='evidence_files')
    op.drop_index('ix_evidence_files_test_id', table_name='evidence_files')
    op.drop_index('ix_evidence_files_status', table_name='evidence_files')
    op.drop_index('ix_evidence_files_cycle_id', table_name='evidence_files')
    op.drop_index('ix_evidence_files_control_id', table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index('ix_control_tests_config_control_id', table_name='control_tests_and_evidences')
    op.drop_table('control_tests_and_evidences')
    op.drop_index('ix_engagement_team_user_id', table_name='engagement_team')
    op.drop_table('engagement_team')
    op.drop_index('ix_control_frameworks_framework_name', table_name='control_frameworks')
    op.drop_table('control_frameworks')
    op.drop_index('ix_control_change_log_to_version', table_name='control_change_log')
    op.drop_index('ix_control_change_log_from_version', table_name='control_change_log')
    op.drop_index('ix_control_change_log_control_id', table_name='control_change_log')
    op.drop_index('ix_control_change_log_changed_by', table_name='control_change_log')
    op.drop_table('control_change_log')
    op.drop_index('ix_config_controls_control_id', table_name='config_controls')
    op.drop_table('config_controls')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_review_cycles_status', table_name='review_cycles')
    op.drop_index('ix_review_cycles_project_lead', table_name='review_cycles')
    op.drop_index('ix_review_cycles_client_id', table_name='review_cycles')
    op.drop_table('review_cycles')
    op.drop_index('ix_control_repository_version_id', table_name='control_repository')
    op.drop_index('ix_control_repository_units_fccg_contact', table_name='control_repository')
    op.drop_index('ix_control_repository_status', table_name='control_repository')
    op.drop_index('ix_control_repository_domain', table_name='control_repository')
    op.drop_index('ix_control_repository_control_owner', table_name='control_repository')
    op.drop_index('ix_control_repository_control_number', table_name='control_repository')
    op.drop_table('control_repository')
    op.drop_index('ix_versions_is_current', table_name='versions', postgresql_where='is_current')
    op.drop_table('versions')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ix_clients_client_name', table_name='clients')
    op.drop_table('clients')
    op.drop_index(
        'ix_control_test_results_cycle_id',
        table_name='control_test_results'
    )

    op.drop_index(
        'ix_control_test_results_control_id',
        table_name='control_test_results'
    )

    op.drop_index(
        'ix_control_test_results_test_id',
        table_name='control_test_results'
    )

    op.drop_table('control_test_results')

    # ### end Alembic commands ###

