"""add sample size to config controls

Revision ID: 449946cfe3db
Revises: a7902845201d
Create Date: 2026-09-03 11:21:06.936573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '449946cfe3db'
down_revision: Union[str, None] = 'a7902845201d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_controls', sa.Column('sample_size', sa.String(length=50), nullable=True))
    op.add_column('config_controls', sa.Column('sample_size_source', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_controls', 'sample_size_source')
    op.drop_column('config_controls', 'sample_size')
    # ### end Alembic commands ###
