"""add sample_no to evidence files

Revision ID: 662cfaa36a76
Revises: 449946cfe3db
Create Date: 2026-09-03 11:41:40.812109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '662cfaa36a76'
down_revision: Union[str, None] = '449946cfe3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_files', sa.Column('sample_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_files', 'sample_no')
    # ### end Alembic commands ###
