"""add evidence_vault_path to clients

Revision ID: 7dd6ab84f99f
Revises: ed90be1d2467
Create Date: 2026-09-02 12:36:08.238290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd6ab84f99f'
down_revision: Union[str, None] = 'ed90be1d2467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('evidence_vault_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'evidence_vault_path')
    # ### end Alembic commands ###
