"""add entity scoping to review cycles and config controls

Revision ID: a7902845201d
Revises: b56ee3f8b0d0
Create Date: 2026-09-02 13:59:56.341480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7902845201d'
down_revision: Union[str, None] = 'b56ee3f8b0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_controls', sa.Column('entity_code', sa.String(length=50), nullable=True))
    op.add_column('config_controls', sa.Column('entity_detail_json', sa.JSON(), nullable=True))
    op.add_column('review_cycles', sa.Column('entity_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_cycles', 'entity_code')
    op.drop_column('config_controls', 'entity_detail_json')
    op.drop_column('config_controls', 'entity_code')
    # ### end Alembic commands ###
