"""add client scoping and source json to control repository

Revision ID: b56ee3f8b0d0
Revises: 7dd6ab84f99f
Create Date: 2026-09-02 13:07:54.955077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56ee3f8b0d0'
down_revision: Union[str, None] = '7dd6ab84f99f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('clients', sa.Column('control_jsons_path', sa.String(length=500), nullable=True))

    # Add nullable first — existing control_repository rows predate client
    # scoping. Every control seeded so far came from the UKMC/Signora seed
    # script, so backfill them onto the Signora client before enforcing
    # NOT NULL.
    op.add_column('control_repository', sa.Column('client_id', sa.BigInteger(), nullable=True))
    op.add_column('control_repository', sa.Column('source_json', sa.JSON(), nullable=True))

    control_repository = sa.table(
        'control_repository', sa.column('client_id', sa.BigInteger())
    )
    clients = sa.table(
        'clients', sa.column('client_id', sa.BigInteger()), sa.column('client_code', sa.String())
    )
    conn = op.get_bind()
    signora_id = conn.execute(
        sa.select(clients.c.client_id).where(clients.c.client_code == 'SIGNORA-SEED')
    ).scalar()
    if signora_id is not None:
        conn.execute(
            control_repository.update()
            .where(control_repository.c.client_id.is_(None))
            .values(client_id=signora_id)
        )

    op.alter_column('control_repository', 'client_id', nullable=False)
    op.create_index('ix_control_repository_client_id', 'control_repository', ['client_id'], unique=False)
    op.create_foreign_key(None, 'control_repository', 'clients', ['client_id'], ['client_id'], onupdate='CASCADE', ondelete='RESTRICT')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'control_repository', type_='foreignkey')
    op.drop_index('ix_control_repository_client_id', table_name='control_repository')
    op.drop_column('control_repository', 'source_json')
    op.drop_column('control_repository', 'client_id')
    op.drop_column('clients', 'control_jsons_path')
    # ### end Alembic commands ###
